# Generated by Django 5.2.3 on 2025-06-30 10:23

from django.db import migrations, models
from datetime import date  # ✅ import date to get current year

class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0003_alumnimessage_leadershipmessage_testimonialsmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadershipmessage',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='alumnimessage',
            name='year_of_completion',
            field=models.IntegerField(
                choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004),
                         (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009),
                         (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014),
                         (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019),
                         (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024),
                         (2025, 2025)],
                default=date.today().year,  # ✅ use current year
            ),
        ),
        migrations.AlterField(
            model_name='alumnimessage',
            name='image',
            field=models.ImageField(upload_to='images/alumni/'),
        ),
        migrations.AlterField(
            model_name='leadershipmessage',
            name='image',
            field=models.ImageField(upload_to='images/leadership/'),
        ),
        migrations.AlterField(
            model_name='testimonialsmessage',
            name='image',
            field=models.ImageField(upload_to='images/testimonials/'),
        ),
    ]
