# Generated by Django 5.2.3 on 2025-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0004_rename_designation_leadershipmessage_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnimessage',
            name='year_of_completion',
            field=models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=BooklandBackend.booklandapp.models.current_year),
        ),
    ]
