# Generated by Django 5.2.3 on 2025-06-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0007_alter_alumnimessage_year_of_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Play Group', 'Play Group'), ('PP1 - PP2', 'PP1 - PP2'), ('Grade 1 - 3', 'Grade 1 - 3'), ('Grade 4 - 6', 'Grade 4 - 6'), ('Junior Secondary', 'Junior Secondary')], max_length=50, unique=True)),
                ('tuition_per_term', models.DecimalField(decimal_places=2, help_text='Enter amount in KES', max_digits=10)),
                ('meals_fee', models.DecimalField(decimal_places=2, help_text='Enter amount in KES', max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, help_text='Enter amount in KES', max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, help_text='Enter amount in KES', max_digits=10)),
                ('fee_structure_file', models.FileField(blank=True, help_text='Upload a PDF file of the fee structure', null=True, upload_to='fee_structures/')),
            ],
        ),
        migrations.AlterField(
            model_name='alumnimessage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
