# Generated by Django 5.2.3 on 2025-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0008_feestructure_alter_alumnimessage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Arts', 'Arts'), ('Sports', 'Sports'), ('Community', 'Community')], max_length=20)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('day', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
