# Generated by Django 5.2.3 on 2025-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='featured_events/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Featured Event',
                'verbose_name_plural': 'Featured Events',
            },
        ),
    ]
