# Generated by Django 5.2.3 on 2025-07-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0010_featuredevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipmessage',
            name='salutation',
            field=models.CharField(default='Mr', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Community', 'Community'), ('Academic', 'Academic'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Workshops', 'Workshops'), ('Conferences', 'Conferences')], max_length=20),
        ),
    ]
