# Generated by Django 5.2.3 on 2025-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0011_leadershipmessage_salutation_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipmessage',
            name='salutation',
            field=models.CharField(default='Mr. ', max_length=10),
        ),
    ]
