# Generated by Django 5.2.3 on 2025-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0012_alter_leadershipmessage_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipmessage',
            name='salutation',
            field=models.CharField(max_length=10),
        ),
    ]
