# Generated by Django 5.2.3 on 2025-07-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0014_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAdmissionDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Term One', 'Term One'), ('Term Two', 'Term Two'), ('Term Three', 'Term Three')], help_text='Name of the admission period (e.g. Term Three)', max_length=50, unique=True)),
                ('deadline_date', models.DateField(help_text='Deadline date for the admission period')),
            ],
            options={
                'verbose_name': 'Key Admission Deadline',
                'verbose_name_plural': 'Key Admission Deadlines',
                'ordering': ['deadline_date'],
            },
        ),
    ]
