# Generated by Django 5.2.3 on 2025-07-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0015_keyadmissiondeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyadmissiondeadline',
            name='name',
            field=models.CharField(choices=[('Term One', 'Term One'), ('Term Two', 'Term Two'), ('Term Three', 'Term Three'), ('Mid-Term One', 'Mid-Term One'), ('Mid-Term Two', 'Mid-Term Two')], help_text='Name of the admission period (e.g. Term Three)', max_length=50, unique=True),
        ),
    ]
