# Generated by Django 5.2.9 on 2025-12-16 08:36

import booklandapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0017_alter_alumnimessage_year_of_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnimessage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnimessage',
            name='year_of_completion',
            field=models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=booklandapp.models.current_year),
        ),
        migrations.AlterField(
            model_name='featuredevent',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_structure_file',
            field=models.URLField(blank=True, help_text='Cloudinary PDF URL', null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyadmissiondeadline',
            name='deadline_date',
            field=models.DateField(help_text='Deadline date'),
        ),
        migrations.AlterField(
            model_name='keyadmissiondeadline',
            name='name',
            field=models.CharField(choices=[('Term One', 'Term One'), ('Term Two', 'Term Two'), ('Term Three', 'Term Three'), ('Mid-Term One', 'Mid-Term One'), ('Mid-Term Two', 'Mid-Term Two')], help_text='Name of the admission period', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='leadershipmessage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialsmessage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
