# Generated by Django 5.2.9 on 2025-12-16 15:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0018_alter_alumnimessage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='fee_structure_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload fee structure PDF', max_length=255, null=True),
        ),
    ]
