# Generated by Django 5.2.9 on 2025-12-16 19:53

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0019_alter_feestructure_fee_structure_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['level'], 'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structures'},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_structure_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload the fee structure PDF (public or private)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='level',
            field=models.CharField(choices=[('Play Group', 'Play Group'), ('PP1 - PP2', 'PP1 - PP2'), ('Grade 1 - 3', 'Grade 1 - 3'), ('Grade 4 - 6', 'Grade 4 - 6'), ('Junior Secondary', 'Junior Secondary')], help_text='Select the school level for this fee structure', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='meals_fee',
            field=models.DecimalField(decimal_places=2, help_text='Meals fee per term in KES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, help_text='Total approximate fee per term in KES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, help_text='Transport fee per term in KES (optional)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='tuition_per_term',
            field=models.DecimalField(decimal_places=2, help_text='Tuition fee per term in KES', max_digits=10),
        ),
    ]
