# Generated by Django 5.2.9 on 2025-12-16 20:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0020_alter_feestructure_options_feestructure_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={},
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_structure_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload PDF file (public)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='level',
            field=models.CharField(choices=[('Play Group', 'Play Group'), ('PP1 - PP2', 'PP1 - PP2'), ('Grade 1 - 3', 'Grade 1 - 3'), ('Grade 4 - 6', 'Grade 4 - 6'), ('Junior Secondary', 'Junior Secondary')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='meals_fee',
            field=models.DecimalField(decimal_places=2, help_text='KES per term', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, help_text='KES total', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, help_text='KES per term', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='tuition_per_term',
            field=models.DecimalField(decimal_places=2, help_text='KES per term', max_digits=10),
        ),
    ]
