# Generated by Django 5.2.9 on 2025-12-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0021_alter_feestructure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='KES total', max_digits=10),
        ),
    ]
