# Generated by Django 5.2.9 on 2025-12-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0022_alter_feestructure_total_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='meals_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='tuition_per_term',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
